"""Add available_sizes to Product

Revision ID: 715050565dd3
Revises: 74667814ae32
Create Date: 2024-07-26 03:57:06.704583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715050565dd3'
down_revision = '74667814ae32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_sizes', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('available_sizes')

    # ### end Alembic commands ###
