"""Add is_admin to User

Revision ID: 74667814ae32
Revises: e83ef7f7ab44
Create Date: 2024-07-26 02:20:56.333556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74667814ae32'
down_revision = 'e83ef7f7ab44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
