"""Add size column to reservation table

Revision ID: c61d4b78a818
Revises: 715050565dd3
Create Date: 2024-07-26 21:38:28.910212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61d4b78a818'
down_revision = '715050565dd3'
branch_labels = None
depends_on = None


# Mettez à jour votre script de migration pour ajouter la colonne sans contrainte NOT NULL
def upgrade():
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
